# Generated by Django 3.2 on 2021-04-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gooditem',
            name='units_of_measurement',
            field=models.CharField(choices=[('L', 'Литры'), ('G', 'Граммы')], max_length=40, verbose_name='Ед.измерения'),
        ),
    ]
