# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(742, 428)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pathLabel = QtWidgets.QLabel(self.centralwidget)
        self.pathLabel.setGeometry(QtCore.QRect(10, 0, 231, 21))
        self.pathLabel.setObjectName("pathLabel")

        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(20, 101, 701, 211))
        self.tableView.setObjectName("tableView")

        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(20, 320, 281, 71))
        self.addButton.setObjectName("addButton")

        self.rmButton = QtWidgets.QPushButton(self.centralwidget)
        self.rmButton.setGeometry(QtCore.QRect(460, 320, 251, 71))
        self.rmButton.setObjectName("rmButton")

        self.path_db_Button = QtWidgets.QPushButton(self.centralwidget)
        self.path_db_Button.setGeometry(QtCore.QRect(10, 30, 321, 41))
        self.path_db_Button.setObjectName("path_db_Button")

        self.db_path = QtWidgets.QLineEdit(self.centralwidget)
        self.db_path.setGeometry(QtCore.QRect(352, 29, 341, 41))
        self.db_path.setObjectName("lineEdit")
        self.db_path.setReadOnly(True)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pathLabel.setText(_translate("MainWindow", "Путь к базе данных:"))
        self.addButton.setText(_translate("MainWindow", "Добавить"))
        self.rmButton.setText(_translate("MainWindow", "Удалить"))
        self.path_db_Button.setText(_translate("MainWindow", "Выбрать путь"))
